### ISSUE TITLE
Library Support for Multi-Relay

### ISSUE THREAD

**Issue by kfrancis** [Marfusios/nostr-client#1]
Any thoughts about writing multi-relay support into the client? It would be nice not to leave that up to the implementation, as it's kind of central to Nostr function and all clients would need to figure that out first before their client could be useful.

**Comment by Marfusios** [comment]
Hey @kfrancis ,

great idea!
Implemented in d4169a18b8cfc7c0df58f681511c2fc7a8a22d7d, class `NostrMultiWebsocketClient`. 
Usage example [here](https://github.com/Marfusios/nostr-client/blob/master/test_integration/Nostr.Client.Sample.Console/Program.cs#L45), deployed in v1.2.0

**Comment by kfrancis** [comment]
Looks really good! I'll check that out!
