### ISSUE TITLE
NIP 99

### ISSUE THREAD

**Issue by DavidGershony** [Marfusios/nostr-client#6]
Can you add support for NIP 99?

**Comment by weex** [comment]
@DavidGershony do you mean just add a Kind or is there other functionality that is needed?

If it's just a kind, this might be generalized to the problem that only included kinds can be generated. Proposed solution for that would be to allow an int to be entered as well.

**Comment by DavidGershony** [comment]
I used the value 30402 cast to NostrKind for the kind property and it works fine, thought there could be a strongly typed message like the NostrZapReceiptEvent but actually I think I'll use NIP 78 instead as the data is really specific to our app.
